import { extract, install } from "@twind/core";
import presetAutoprefix from "@twind/preset-autoprefix";
import presetTailwind from "@twind/preset-tailwind";
import { h } from "preact";
import { renderToString } from "preact-render-to-string";
import { BaseLayout } from "./layouts/BaseLayout.tsx";

// Initialize Twind with autoprefix and tailwind presets in class dark mode
install({
  presets: [presetAutoprefix(), presetTailwind()],
  darkMode: "class",
});

export interface RenderHtmlOptions {
  title?: string;
  scripts?: string[];
  styles?: string[];
  status?: number;
  headers?: Record<string, string>;
}

export const SECURITY_HEADERS: Record<string, string> = {
  "content-type": "text/html; charset=utf-8",
  "x-content-type-options": "nosniff",
  "x-frame-options": "SAMEORIGIN",
  "referrer-policy": "strict-origin-when-cross-origin",
};

/**
 * Renders a Preact VNode to an HTML string with Twind CSS extraction,
 * wrapping in BaseLayout if not already an HTML document, and returns a standard HTTP Response.
 */
export function renderHtmlResponse(
  // deno-lint-ignore no-explicit-any
  vnode: any,
  options?: RenderHtmlOptions,
): Response {
  let initialHtml = renderToString(vnode);

  // If the rendered component does not already include <html>, wrap it in BaseLayout
  if (!initialHtml.includes("<html") && !initialHtml.includes("<HTML")) {
    initialHtml = renderToString(
      h(BaseLayout, {
        title: options?.title,
        scripts: options?.scripts,
        styles: options?.styles,
        children: vnode,
      }),
    );
  }

  // Extract minimal Tailwind CSS generated by Twind
  const { html, css } = extract(initialHtml);

  let doc = html;
  const styleTag = css ? `<style id="__twind">${css}</style>` : "";

  // Inject extracted CSS into head
  if (doc.includes("</head>")) {
    doc = doc.replace("</head>", `${styleTag}</head>`);
  } else if (doc.includes("</HEAD>")) {
    doc = doc.replace("</HEAD>", `${styleTag}</HEAD>`);
  } else {
    doc = `${styleTag}${doc}`;
  }

  // Ensure doctype is present
  if (!doc.startsWith("<!DOCTYPE html>") && !doc.startsWith("<!doctype html>")) {
    doc = `<!DOCTYPE html>\n${doc}`;
  }

  const status = options?.status ?? 200;
  const headers = {
    ...SECURITY_HEADERS,
    ...(options?.headers ?? {}),
  };

  return new Response(doc, {
    status,
    headers,
  });
}
